export enum InvokeChannels {
  createProfile = 'create-profile',
  renameProfile = 'rename-profile',
  deleteProfile = 'delete-profile',
  login = 'login',
  logout = 'logout',
  updateUISettings = 'update-ui-settings',
  createFolder = 'create-folder',
  createSession = 'create-session',
  updateFilters = 'update-filters',
  createCard = 'create-card',
  refetchProfile = 'refetch-profile',
  refetchSessions = 'refetch-sessions',
  refetchTags = 'refetch-tags',
  refetchFilters = 'refetch-filters',
  getCardsPage = 'get-cards-page',
}
