export enum InvokeChannels {
  createProfile = 'create-profile',
  renameProfile = 'rename-profile',
  deleteProfile = 'delete-profile',
  login = 'login',
  logout = 'logout',
  updateUISettings = 'update-ui-settings',
  updateOjContext = 'update-oj-context',
  updateOjCache = 'update-oj-cache',
  getOjProblem = 'get-oj-problem',
  fetchHistoryPage = 'fetch-history-page',
  updateSnapshot = 'update-snapshot',
  updateGraph = 'update-graph',
  createFolder = 'create-folder',
  createContest = 'create-contest',
  getContest = 'get-contest',
  renameContest = 'rename-contest',
  contestExists = 'contest-exists',
  addContestProblem = 'add-contest-problem',
  updateContestNotes = 'update-contest-notes',
}
