export enum InvokeChannels {
  updateCurrOj = 'update-curr-oj',
  updateCurrPage = 'update-curr-page',
  createProfile = 'create-profile',
  login = 'login',
  logout = 'logout',
  updateOjCache = 'update-oj-cache',
  getOjProblem = 'get-oj-problem',
  setCurrSnapshotSolvedDate = 'set-curr-snapshot-solved-date',
  updateOjFilters = 'update-oj-filters',
  fetchHistoryPage = 'fetch-history-page',
  setCurrOjSnapshot = 'set-curr-oj-snapshot',
  renameProfile = 'rename-profile',
  deleteProfile = 'delete-profile',
  getContest = 'get-contest',
  createContest = 'create-contest',
  addCurrContestProblem = 'add-curr-contest-problem',
  updateCurrContestNotes = 'update-curr-contest-notes',
  updateCurrContestProblem = 'update-curr-contest-problem',
  toggleCurrContestProblemFlag = 'toggle-curr-contest-problem-flag',
  deleteCurrContestProblem = 'delete-curr-contest-problem',
}
