import './invokes/profile';
import './invokes/ui';
import './invokes/ojContext';
import './invokes/cache';
import './invokes/ojPool';
import './invokes/history';
import './invokes/contests';
import './invokes/graph';
import '@interapp/components/Explorer/receiver/invokes';
