export enum InvokeChannels {
  createProfile = 'create-profile',
  renameProfile = 'rename-profile',
  deleteProfile = 'delete-profile',
  login = 'login',
  logout = 'logout',
  incrementGraph = 'increment-graph',
  createFolder = 'create-folder',
  createNote = 'create-note',
  updateUISettings = 'update-ui-settings',
  refetchProfile = 'refetch-profile',
  refetchTabs = 'refetch-tabs',
  // ----------------------------------
  updateSettings = 'update-settings',
  updateFilters = 'update-filters',
  createCard = 'create-card',
  deleteCard = 'delete-card',
  updateCard = 'update-card',
  refetchSessions = 'refetch-sessions',
  refetchTags = 'refetch-tags',
  refetchFilters = 'refetch-filters',
  getCardsPage = 'get-cards-page',
  getStatistics = 'get-statistics',
  clearFilteredBucket = 'clear-filtered-bucket',
  clearFilteredFrequency = 'clear-filtered-frequency',
  getFlashcard = 'get-flashcard',
}
