export enum InvokeChannels {
  createProfile = 'create-profile',
  renameProfile = 'rename-profile',
  deleteProfile = 'delete-profile',
  login = 'login',
  logout = 'logout',
  incrementGraph = 'increment-graph',
  createFolder = 'create-folder',
  createNote = 'create-note',
  updateUISettings = 'update-ui-settings',
  refetchProfile = 'refetch-profile',
  refetchTabs = 'refetch-tabs',
  updateTabs = 'update-tabs',
  getNote = 'get-note',
  updateNote = 'update-note',
  getStatistics = 'get-statistics',
  recomputeQueues = 'recompute-queues',
  getFlashcard = 'get-flashcard',
  updateSettings = 'update-settings',
  updateFilters = 'update-filters',
  //
  clearFilteredBucket = 'clear-filtered-bucket',
  clearFilteredFrequency = 'clear-filtered-frequency',
}
